modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${displayName}"
authors = "Ran, CodeF53"
description = '''
A small utility mod for Ran (Not to be confused with Ran's utility library "Ranitils")

Special thanks to these people:
CodeF53 (For helping me make mod)
plusls (For creating OMMC)
Luna (For creating Elytra Recast)

'''
logoFile = "assets/${id}/icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"